services:
  nginx:
    image: bitnami/nginx:latest
    container_name: lepp-nginx
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./:/app
      - ./docker/nginx/mrp.conf:/opt/bitnami/nginx/conf/server_blocks/mrp.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./docker/logs/nginx:/opt/bitnami/nginx/logs
    networks:
      - lepp-net

  php-fpm:
    image: bitnami/php-fpm:latest
    container_name: lepp-php-fpm
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/logs/php-fpm:/opt/bitnami/php/var/log
    networks:
      - lepp-net

  postgresql:
    image: bitnami/postgresql:latest
    container_name: lepp-postgresql
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
      - ./docker/logs/postgresql:/opt/bitnami/postgresql/logs
    networks:
      - lepp-net

  valkey:
    image: bitnami/valkey:latest
    container_name: lepp-valkey
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/bitnami/valkey/data
    env_file:
      - .env.docker
    environment:
      - VALKEY_DISABLE_THREADS=1
    networks:
      - lepp-net

networks:
  lepp-net:
    driver: bridge

volumes:
  postgresql_data:
  valkey_data:
